### ISSUE TITLE
響應式佈局個半細、細視窗下冇見語言切換撳掣

### ISSUE THREAD

**Issue by LaiJoengzit** [CanCLID/jyutping.org#17]
半細視窗「輸入法」、「關於」頁面冇
細視窗（手機）全部冇

**Comment by laubonghaudoi** [comment]
呢個係 Hugo 模板限制，我都唔識點解決，如果你有解決辦法嘅話務必PR，唔該晒。

**Comment by LaiJoengzit** [comment]
> 呢個係 Hugo 模板限制，我都唔識點解決，如果你有解決辦法嘅話務必PR，唔該晒。

我都毋識Hugo啊……Hugo限制到撳掣擺邊笪埞噶咩？

**Comment by laubonghaudoi** [comment]
呢個係模板決定㗎，我揀嘅呢個docsy模板就係噉，一係你睇下可唔可以改個模板等佢可以手機嗰陣都可以出語言掣
