### ISSUE TITLE
JavaScript (and sound) will not load in Safari

### ISSUE THREAD

**Issue by ProfFan** [CanCLID/jyutping.org#41]
See https://stackoverflow.com/questions/64406194/content-security-policy-hash-not-recognized-by-safari-13-1-2

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src

Safari does not support CSP 3.0 hash attribute.

Thank you for this wonderful site!

**Comment by laubonghaudoi** [comment]
呢個問題我哋改唔到。呢個網站係用[Hugo](https://gohugo.io/) 再加 [docsy](https://github.com/google/docsy)模板生成嘅，你可唔可以去佢哋嗰度開 issue？

另外我喺 iOS 16.0 嘅 Safari 上面試咗下，啲錄音都可以正常播放。
