### ISSUE TITLE
Practice Songs return Internal Server Error

### ISSUE THREAD

**Issue by yilverdeja** [CanCLID/jyutping.org#48]
I'm not able to play the songs found within the `/blog/song` page. All the audio controls show that it has a length of 0 seconds.

![image](https://github.com/CanCLID/jyutping.org/assets/29952939/106d447e-ed52-4cb3-bb32-47461139bf0f)

I tried accessing the songs [directly following the audio path](https://jyutping.org/song/maanboujansanglou.mp3), and it returns an Internal Server Error.

**Comment by laubonghaudoi** [comment]
已經修復 https://jyutping.org/blog/song/

**Comment by graphemecluster** [comment]
@laubonghaudoi 你乜都冇做過喎，做咩閂咗佢？
其實我幾個月前已經喺 CanCLID group 講過播唔到呢個問題，到而家都係噉

**Comment by yilverdeja** [comment]
I checked now, and it's working fine. Thanks @laubonghaudoi !

I think the change was made on Netlify @graphemecluster . The site was redeployed this morning when he commented on this thread and closed the issue.

**Comment by graphemecluster** [comment]
Ah, missed that. But at least in my case I still get `錯誤`s after a minute loading the audios. I reloaded the page many times, tried different browsers and still got the same result.

**Comment by laubonghaudoi** [comment]
佢出呢個錯係因為Netlify出咗個新嘅咩asset optimization，跟住啲 mp3 文件因為佔用佢太多帶寬所以停咗，我閂咗佢呢個優化跟住重新部署所以我呢邊測試過係冇問題嘅。首漫步人生路前8秒都係靜音嚟嘅要到第9秒先開始有聲，你係點出錯？
