### ISSUE TITLE
Secure Connection Failed / site can’t be reached 2023-12-25

### ISSUE THREAD

**Issue by yawnoc** [CanCLID/jyutping.org#51]
<<https://www.jyutping.org/>> fails to load, 2023-12-25 00:15 (UTC+8).

## Firefox 115.6.0esr

> Secure Connection Failed
>
> An error occurred during a connection to www.jyutping.org. PR_END_OF_FILE_ERROR
>
> Error code: PR_END_OF_FILE_ERROR
> - The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
> - Please contact the website owners to inform them of this problem.

## Chromium 120.0.6099.129

> This site can’t be reached
>
> www.jyutping.org unexpectedly closed the connection.
>
> Try:
> - Checking the connection
> - Checking the proxy and the firewall
>
> ERR_CONNECTION_CLOSED

## Failed urlscan.io scan

<https://urlscan.io/result/21029901-18ae-437c-ad03-f738131bac84/>

> We could not scan this website!
>
> This can happen for multiple reasons:
>
> - The site could not be contacted (DNS or generic network issues)
> - The site uses insecure TLS (weak ciphers e.g.)
> - The site requires HTTP authentication
>
> Take a look at the [JSON output](https://urlscan.io/api/v1/result/21029901-18ae-437c-ad03-f738131bac84/) or the screenshot to determine a possible cause.

**Comment by laubonghaudoi** [comment]
好似係因為咩 SSL 證書過期，我啱先又更新咗，你試下得唔得？

**Comment by yawnoc** [comment]
得咗
