### ISSUE TITLE
[Typo] 廣拼 equivalent of 粵拼 `s` should be `s / x` instead of `c / x`

### ISSUE THREAD

**Issue by aafulei** [CanCLID/jyutping.org#56]
在`./content/zh-yue-hant/blog/table.md`的表格中，对应粤拼`s`的广拼应当是`s / x`，而不是`c / x`。请更正。

**Comment by laubonghaudoi** [comment]
你開個PR？

**Comment by aafulei** [comment]
Sorry I don't have time.

**Comment by laubonghaudoi** [comment]
@ngchinghung 噉要麻煩你嚟改

**Comment by Linfye** [comment]
I just found thiis repo and am interested in Jyutping. Can you assign this to me? I am available recently. @laubonghaudoi

**Comment by laubonghaudoi** [comment]
搞掂
